by Annisa DSML 43

## Basic Calculation in Python

In [ ]:
# A. Calculation - Basic Calculation in Python
print("=== A. Basic Calculations ===")

# Addition
print("5 + 3 =", 5 + 3)

# Subtraction
print("10 - 4 =", 10 - 4)

# Multiplication
print("7 * 6 =", 7 * 6)

# Division
print("15 / 4 =", 15 / 4)

# Integer Division
print("15 // 4 =", 15 // 4)

# Modulus
print("15 % 4 =", 15 % 4)

# Exponentiation
print("2 ** 5 =", 2 ** 5)

# Order of operations
print("(5 + 3) * 2 =", (5 + 3) * 2)

print((10 + 5) * (20 - 7) / 3)

print(2 ** 3 + 5 * 4)

=== A. Basic Calculations ===
5 + 3 = 8
10 - 4 = 6
7 * 6 = 42
15 / 4 = 3.75
15 // 4 = 3
15 % 4 = 3
2 ** 5 = 32
(5 + 3) * 2 = 16
65.0
28


Latihan:

Hitung (10 + 5) * (20 - 7) / 3

Berapa hasil 2 ** 3 + 5 * 4?

In [ ]:
soal1 = (10 + 5) * (20 - 7) / 3
soal2 = (2 ** 3 + 5 * 4 )/7

print(soal1)
print(soal2)

65.0
4.0


hitung (20+5x12) - ((20/3)+5) + 200 / 5

In [ ]:
soal3 = (20+5*12) - ((20/3)+5) + 200/5
print(soal3)

108.33333333333333


berapa hasil dari 5 pangkat 5 dikali 2 dibagi 3

In [ ]:
soal4 = 5**5*2/3
print(soal4)

2083.3333333333335


soal 5: hitunglah 20+5-
(12x4) dipangkatkan dg pangkat 3 dan hasil akhir semua nya di kurangi dg 100

In [ ]:
print(((20+5-(12*4))**3)-100)

-12267


soal 6: ibu beli telor 10 buah, lalu pecah 3 dan ibu beli lagi 20, lalu ibu bagi tetangga 10, dan sisa akhir telur ibu di pangkatkan 2

In [ ]:
print((10-3+20-10)**2)

289


## Data Types

In [ ]:
# B. Data Types
print("\n=== B. Data Types ===")

# 1. Character (String in Python)
char_var = 'a' #krn di apit petik ''
string_var = "Hello Python"
print("\nCharacter/String:")
print(char_var, type(char_var)) #cek tipe
print(string_var, type(string_var))

# Numeric - Integer
int_var = 25
print("\nInteger:")
print(int_var, type(int_var))

# Numeric - Float
float_var = 3.14159
print("\nFloat:")
print(float_var, type(float_var))

# Logical (Boolean in Python)
bool_var1 = True
bool_var2 = False
print("\nBoolean:")
print(bool_var1, type(bool_var1))
print(bool_var2, type(bool_var2))
print("5 > 3:", 5 > 3)

# Complex
complex_var = 3 + 4j
print("\nComplex:")
print(complex_var, type(complex_var))
print("Real part:", complex_var.real)
print("Imaginary part:", complex_var.imag)


=== B. Data Types ===

Character/String:
a <class 'str'>
Hello Python <class 'str'>

Integer:
25 <class 'int'>

Float:
3.14159 <class 'float'>

Boolean:
True <class 'bool'>
False <class 'bool'>
5 > 3: True

Complex:
(3+4j) <class 'complex'>
Real part: 3.0
Imaginary part: 4.0


In [ ]:
data = 3.14
print(type(data))

<class 'float'>


In [ ]:
test = 3 + 4j
print(type(test))

<class 'complex'>


Latihan:

Buat variabel harga = 15000 dan jumlah = 3, lalu hitung total harga.

Cek apakah 10 + 5 == 15 menghasilkan True atau False.

In [ ]:
harga = 15000
jumlah = 3

total_harga = harga * jumlah
print("Total harga:", total_harga)

print("10 + 5 == 15:", 10 + 5 == 15)

Total harga: 45000
10 + 5 == 15: True


Buat variabel bernama Jumlah Siswa yang dimana setiap kelasnya terdiri dari 30 dan saat ini terdapat 3 kelas, hitung total seluruh siswa dengan rapih

In [ ]:
jumlah_siswa = 30
jumlah_kelas = 3
hasil = jumlah_siswa*jumlah_kelas
print(hasil)

90


budi memiliki gaji bulanan sebesar 15jt gross (kotor), dia di haruskan bayar pajak sebesar 20%, lalu dari situ dia memberi ke istri 15% dan orang tua nya 10%, sisa uang budi di akhir brp?

In [ ]:
gaji = 15000000
pajak = gaji * 0.20
jatah_istri = gaji * 0.15
jatah_ortu = gaji * 0.10
sisa_uang = gaji - pajak - jatah_istri - jatah_ortu
print("Sisa uang Budi sebesar:", sisa_uang)

Sisa uang Budi sebesar: 8250000.0


In [ ]:
#answer:
gaji_budi = 15000000
pajak = 0.2
istri = 0.15
ortu = 0.1
total_pajak = gaji_budi * pajak
total_istri = (gaji_budi-total_pajak)*istri
total_ortu = (gaji_budi-total_pajak)*ortu
gaji_akhir = gaji_budi-total_pajak-total_istri-total_ortu

print("Total Pajak : ", total_pajak)
print("Total yang diberikan ke istri : ",total_istri)
print("Total yang diberikan ke ortu : ",total_ortu)
print("Gaji yang diterima Budi : ", gaji_akhir)

Total Pajak :  3000000.0
Total yang diberikan ke istri :  1800000.0
Total yang diberikan ke ortu :  1200000.0
Gaji yang diterima Budi :  9000000.0


## Data Structures

In [ ]:
# C. Data Structures
print("\n=== C. Data Structures ===")

# 1. List (ordered, mutable, allows duplicates)
print("\n1. Lists:")
my_list = [1, 2, 3, 'apple', 'banana', True]
print("Original list:", my_list)
print("Type:", type(my_list))



=== C. Data Structures ===

1. Lists:
Original list: [1, 2, 3, 'apple', 'banana', True]
Type: <class 'list'>


In [ ]:
type(my_list)

list

In [ ]:
my_list.append('Pear') #untuk nambahin pear
print(my_list)

[1, 2, 3, 'apple', 'banana', True, 'Pear']


In [ ]:
my_list.append('orange')
print(my_list)

[1, 2, 3, 'apple', 'banana', True, 'Pear', 'orange']


In [ ]:
# List operations
my_list.append('orange')  # Add item
print("After append:", my_list)
my_list.remove(2)  # Remove item
print("After remove:", my_list)
print("Index 3:", my_list[3])  # Access by index
my_list[1] = 'pear'  # Modify item
print("After modification:", my_list)

After append: [1, 2, 3, 'apple', 'banana', True, 'Pear', 'orange', 'orange']
After remove: [1, 3, 'apple', 'banana', True, 'Pear', 'orange', 'orange']
Index 3: banana
After modification: [1, 'pear', 'apple', 'banana', True, 'Pear', 'orange', 'orange']


In [ ]:
my_list

[1, 'pear', 'apple', 'banana', True, 'Pear', 'orange', 'orange']

In [ ]:
my_list.remove('orange')
print(my_list)

[1, 'pear', 'apple', 'banana', True, 'Pear', 'orange']


In [ ]:
my_list.append('Pear')
print(my_list)

[1, 'pear', 'apple', 'banana', True, 'Pear', 'orange', 'Pear']


In [ ]:
my_list[0], my_list[2] = my_list[2], my_list[0]
print(my_list)

['apple', 'pear', 1, 'banana', True, 'Pear', 'orange', 'Pear']


In [ ]:
my_list.remove('Pear')
print(my_list)

['apple', 'pear', 1, 'banana', True, 'orange', 'Pear']


In [ ]:
print(my_list[-2])

orange


In [ ]:
#Dictionary
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}
print(my_dict)

{'name': 'John', 'age': 30, 'city': 'New York'}


In [ ]:
#untuk ubah value
my_dict['age'] = 31
print(my_dict)

{'name': 'John', 'age': 31, 'city': 'New York'}


In [ ]:
my_dict['city'] = 'Los Angeles'
print(my_dict)

{'name': 'John', 'age': 31, 'city': 'Los Angeles'}


In [ ]:
my_dict['name'] = 'ipul'
print(my_dict)

{'name': 'ipul', 'age': 31, 'city': 'Los Angeles'}


In [ ]:
#nambahin key dan value
my_dict['job'] = 'Data Scientist'
print(my_dict)

{'name': 'ipul', 'age': 31, 'city': 'Los Angeles', 'job': 'Data Scientist'}


In [ ]:
#untuk ngapus
del my_dict['age']
print(my_dict)

{'name': 'ipul', 'city': 'Los Angeles', 'job': 'Data Scientist'}


In [ ]:
my_dict['country'] = 'US'
print(my_dict)

{'name': 'ipul', 'city': 'Los Angeles', 'job': 'Data Scientist', 'country': 'US'}


## Notes for Learning

In [ ]:
# 2. Tuple (ordered, immutable, allows duplicates)
print("\n2. Tuples:")
my_tuple = (1, 3, 5, 'apple', 'banana')
print("Original tuple:", my_tuple)
print("Type:", type(my_tuple))

# Tuple operations
print("Index 2:", my_tuple[2])  # Access by index
print("Length:", len(my_tuple))
# my_tuple[1] = 'pear'  # This would raise an error as tuples are immutable

# Tuple unpacking
a, b, c, d, e = my_tuple
print("Unpacked:", a, b, c, d, e)


2. Tuples:
Original tuple: (1, 3, 5, 'apple', 'banana')
Type: <class 'tuple'>
Index 2: 5
Length: 5
Unpacked: 1 3 5 apple banana


In [ ]:
my_tuple.append('banana') #tidak bisa di tambahkan, maka akan error

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
# 3. Set (unordered, mutable, no duplicates)
print("\n3. Sets:")
my_set = {1, 2, 3, 4, 4, 2, 'apple'}
print("Original set:", my_set)  # Duplicates are automatically removed
print("Type:", type(my_set))

# Set operations
my_set.add('banana')  # Add element
print("After add:", my_set)
my_set.remove(2)  # Remove element
print("After remove:", my_set)

# Set operations
other_set = {3, 4, 5, 'pear'}
print("Union:", my_set.union(other_set))
print("Intersection:", my_set.intersection(other_set))


3. Sets:
Original set: {1, 2, 3, 4, 'apple'}
Type: <class 'set'>
After add: {'banana', 1, 2, 3, 4, 'apple'}
After remove: {'banana', 1, 3, 4, 'apple'}
Union: {'banana', 1, 'pear', 3, 4, 5, 'apple'}
Intersection: {3, 4}


In [ ]:
# 4. Dictionary (key-value pairs, unordered, mutable)
print("\n4. Dictionaries:")
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}
print("Original dictionary:", my_dict)
print("Type:", type(my_dict))

# Dictionary operations
print("Name:", my_dict['name'])  # Access by key
my_dict['age'] = 31  # Modify value
print("After modification:", my_dict)
my_dict['job'] = 'Engineer'  # Add new key-value pair
print("After adding:", my_dict)
del my_dict['city']  # Remove key-value pair
print("After deletion:", my_dict)


4. Dictionaries:
Original dictionary: {'name': 'John', 'age': 30, 'city': 'New York'}
Type: <class 'dict'>
Name: John
After modification: {'name': 'John', 'age': 31, 'city': 'New York'}
After adding: {'name': 'John', 'age': 31, 'city': 'New York', 'job': 'Engineer'}
After deletion: {'name': 'John', 'age': 31, 'job': 'Engineer'}


In [ ]:
# 5. Vector (in Python, we typically use lists or numpy arrays)
print("\n5. Vectors:")
# Using lists as vectors
vector = [1, 2, 3, 4, 5]
print("Vector as list:", vector)

# Vector operations
# Element-wise addition
vector2 = [6, 7, 8, 9, 10]
added = [v1 + v2 for v1, v2 in zip(vector, vector2)]
print("Element-wise addition:", added)

# Scalar multiplication
scalar = 2
multiplied = [x * scalar for x in vector]
print("Scalar multiplication:", multiplied)


5. Vectors:
Vector as list: [1, 2, 3, 4, 5]
Element-wise addition: [7, 9, 11, 13, 15]
Scalar multiplication: [2, 4, 6, 8, 10]


In [ ]:
# Matrices (2D lists or numpy arrays)
print("\n6. Matrices:")
# Using list of lists
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print("Matrix:")
for row in matrix:
    print(row)

# Matrix operations
# Accessing elements
print("Element at row 1, column 2:", matrix[1][2])

# Transposing matrix
transposed = [[row[i] for row in matrix] for i in range(len(matrix[0]))]
print("\nTransposed matrix:")
for row in transposed:
    print(row)


6. Matrices:
Matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Element at row 1, column 2: 6

Transposed matrix:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [ ]:
# Arrays (using numpy for efficient numerical operations)
import numpy as np

print("\n7. Arrays with NumPy:")
# Creating numpy arrays
arr = np.array([1, 2, 3, 4, 5])
print("1D array:", arr)
print("Type:", type(arr))

# 2D array
matrix_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\n2D array:")
print(matrix_np)

# Array operations
print("\nArray operations:")
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Matrix multiplication:")
print(np.dot(matrix_np, matrix_np))


7. Arrays with NumPy:
1D array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array operations:
Sum: 15
Mean: 3.0
Matrix multiplication:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Latihan:

Buat list angka = [5, 2, 8, 1], lalu urutkan dengan .sort().

Buat dictionary motor = {"merk": "Honda", "cc": 150}, lalu tambahkan "warna": "merah".

In [ ]:
#untuk mengurutkan => pake sort
angka = [5,2,8,1]
angka.sort()
angka

[1, 2, 5, 8]

In [ ]:
motor = {"merk": "Honda", "cc": 150}
motor["warna"] = "merah"
motor

{'merk': 'Honda', 'cc': 150, 'warna': 'merah'}

Buatlah dictionary yang dimana kalian harus membuat satu variabel yang mencakup informasi berikut: namanya adalah Marco, usianya 28, saat ini bekerja sebagai Machine Learning Engineer yang berada di kota Tokyo negara Japan

Pada bagia akhir setelah berhasil dibuat, tambahkan negara asal, yaitu Indonesia

In [ ]:
data = {'nama': 'marco', 'usia':'28', 'pekerjan': 'ML Engineer', 'kota': 'tokyo', 'negara': 'japan'}
print(data)

{'nama': 'marco', 'usia': '28', 'pekerjan': 'ML Engineer', 'kota': 'tokyo', 'negara': 'japan'}


In [ ]:
data['negara asal'] = 'indonesia'
print(data)

{'nama': 'marco', 'usia': '28', 'pekerjan': 'ML Engineer', 'kota': 'tokyo', 'negara': 'japan', 'negara asal': 'indonesia'}
